### ISSUE TITLE
Licença de uso

### ISSUE THREAD

**Issue by beatrizmilz** [ipeaGIT/censobr_oficina_abep_2024#3]
Olá!

@rafapereirabr Gostaria de saber qual é a [licença de uso](https://choosealicense.com/) do material.

Eu vou dar um workshop no cebrap sobre visualização de dados, mas o material foi feito anteriormente usando dados do pacote [abjData](https://abjur.github.io/abjData/), que tem algumas informações sobre IDH municipal baseado nos dados do censo (a fonte original é o PNUD: https://www.undp.org/pt/brazil/atlas-dos-municipios). Porém esses dados estão disponíveis até 2010.

Pensei em adaptar os exemplos usando o pacote `{censobr}`. Mesmo que alguns exemplos sejam para 2010, pelo menos os códigos já ficarão disponíveis para usar quando os dados de 2022 estiverem disponíveis.

Pensei em adaptar os exemplos e indicar como referência e inspiração/basear em exemplos dessa oficina da ABEP, mas queria saber se é ok para os autores!

Abraços

**Comment by rafapereirabr** [comment]
Oi Bia. Acabei de incluir um arquivo com a licença, que é `"GNU GPLv3"` desde que indicada a autoria. Então fique a vontade para utilizar ou adaptar os exemplos desse curto aqui e das vignettes dos pacotes tambem.

**Comment by beatrizmilz** [comment]
Obrigada!

> Oi Bia. Acabei de incluir um arquivo com a licença, que é `"GNU GPLv3"` desde que indicada a autoria. Então fique a vontade para utilizar ou adaptar os exemplos desse curto aqui e das vignettes dos pacotes tambem.
